# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@mozilla/readability-0.4.1" = {
      name = "_at_mozilla_slash_readability";
      packageName = "@mozilla/readability";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mozilla/readability/-/readability-0.4.1.tgz";
        sha512 = "yar/f0w0fRUVM895s6yd5Z2oIxjG/6c3ROB/uQboSOBaDlri/nqI4aKtdqrldWciTLcdpjB2Z6MiVF2Bl9b8LA==";
      };
    };
    "darkreader-4.9.34" = {
      name = "darkreader";
      packageName = "darkreader";
      version = "4.9.34";
      src = fetchurl {
        url = "https://registry.npmjs.org/darkreader/-/darkreader-4.9.34.tgz";
        sha512 = "Nq8rxXLUD/0TZ9qzvAkZDAbxRVrbPdwKPTqnx7sEk1RLTK6IyQNu2d1GdffPVEhXgK1SvSeETWDwo443tSf0fg==";
      };
    };
  };
  args = {
    name = "eaf-browser";
    packageName = "eaf-browser";
    version = "0.0.1";
    src = ./.;
    dependencies = [
      sources."@mozilla/readability-0.4.1"
      sources."darkreader-4.9.34"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
